export const dashboardData = {
  metrics: {
    totalEmployees: 247,
    totalEmployeesChange: "+12%",
    newHires: 8,
    newHiresChange: "+25%",
    departments: 12,
    departmentsChange: "0%",
    activeProjects: 34,
    activeProjectsChange: "+18%",
  },
  quickStats: {
    employeesOnLeave: 15,
    pendingLeaveRequests: 7,
    birthdaysThisWeek: 3,
    anniversariesThisMonth: 5,
    performanceReviewsDue: 12,
    openPositions: 6,
  },
  recentActivity: [
    {
      id: 1,
      type: "hire",
      employee: "Alice Chen",
      action: "New employee onboarding completed",
      time: "2 hours ago",
      department: "Engineering",
    },
    {
      id: 2,
      type: "leave",
      employee: "David Wilson",
      action: "Vacation request approved",
      time: "4 hours ago",
      department: "Marketing",
    },
    {
      id: 3,
      type: "review",
      employee: "Sarah Johnson",
      action: "Performance review submitted",
      time: "6 hours ago",
      department: "Product",
    },
    {
      id: 4,
      type: "promotion",
      employee: "Michael Brown",
      action: "Promoted to Senior Developer",
      time: "1 day ago",
      department: "Engineering",
    },
    {
      id: 5,
      type: "training",
      employee: "Lisa Anderson",
      action: "Completed leadership training",
      time: "2 days ago",
      department: "HR",
    },
  ],
  pendingActions: [
    {
      id: 1,
      type: "leave_request",
      title: "Emily Davis - Vacation Request",
      description: "2 weeks vacation from Feb 15-28",
      priority: "high",
      dueDate: "Today",
    },
    {
      id: 2,
      type: "performance_review",
      title: "Q4 Performance Reviews",
      description: "12 reviews pending completion",
      priority: "medium",
      dueDate: "This week",
    },
    {
      id: 3,
      type: "onboarding",
      title: "New Hire Onboarding",
      description: "3 new employees starting Monday",
      priority: "high",
      dueDate: "Jan 29",
    },
    {
      id: 4,
      type: "compliance",
      title: "Training Compliance",
      description: "8 employees need safety training",
      priority: "medium",
      dueDate: "Next week",
    },
  ],
  teamInsights: {
    topPerformers: [
      { name: "Sarah Johnson", department: "Product", score: 4.8 },
      { name: "Michael Chen", department: "Engineering", score: 4.7 },
      { name: "Emily Davis", department: "Design", score: 4.6 },
    ],
    departmentGrowth: [
      { name: "Engineering", employees: 85, growth: "+15%" },
      { name: "Sales", employees: 42, growth: "+8%" },
      { name: "Marketing", employees: 28, growth: "+12%" },
      { name: "Product", employees: 35, growth: "+20%" },
    ],
  },
  upcomingEvents: [
    {
      id: 1,
      type: "birthday",
      name: "John Smith",
      date: "Today",
      department: "Sales",
    },
    {
      id: 2,
      type: "anniversary",
      name: "Lisa Chen",
      date: "Tomorrow",
      department: "Engineering",
      years: 3,
    },
    {
      id: 3,
      type: "birthday",
      name: "Robert Johnson",
      date: "Jan 25",
      department: "Marketing",
    },
    {
      id: 4,
      type: "anniversary",
      name: "Maria Garcia",
      date: "Jan 28",
      department: "HR",
      years: 5,
    },
  ],
};
