export const statusCards = [
  {
    title: "In Office",
    value: "102",
    icon: "🏢",
    color: "bg-blue-500",
    bgColor: "bg-blue-50",
    textColor: "text-blue-600",
  },
  {
    title: "Remote",
    value: "44",
    icon: "🏠",
    color: "bg-orange-500",
    bgColor: "bg-orange-50",
    textColor: "text-orange-600",
  },
  {
    title: "On Leave",
    value: "9",
    icon: "😴",
    color: "bg-red-500",
    bgColor: "bg-red-50",
    textColor: "text-red-600",
  },
  {
    title: "Pending Requests",
    value: "3",
    icon: "📋",
    color: "bg-purple-500",
    bgColor: "bg-purple-50",
    textColor: "text-purple-600",
  },
];

export const getWeeklyEmployeeData = () => [
  {
    id: 1,
    name: "Do Thi Nga",
    role: "FE",
    avatar: "DN",
    weekSchedule: [
      { day: "Mon", morning: "office", afternoon: "office", hours: "8h" },
      { day: "Tue", morning: "office", afternoon: "office", hours: "8h" },
      { day: "Wed", morning: "remote", afternoon: "office", hours: "7h 30m" },
      { day: "Thu", morning: "office", afternoon: "office", hours: "8h 15m" },
      { day: "Fri", morning: "office", afternoon: "leave", hours: "4h" },
      { day: "Sat", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Sun", morning: "leave", afternoon: "leave", hours: "0h" },
    ],
    totalWeekHours: "35h 45m",
  },
  {
    id: 2,
    name: "Luong Quy Tan",
    role: "FE",
    avatar: "LQ",
    weekSchedule: [
      { day: "Mon", morning: "remote", afternoon: "remote", hours: "8h" },
      { day: "Tue", morning: "remote", afternoon: "office", hours: "7h 45m" },
      { day: "Wed", morning: "office", afternoon: "remote", hours: "8h" },
      { day: "Thu", morning: "remote", afternoon: "leave", hours: "4h" },
      { day: "Fri", morning: "office", afternoon: "office", hours: "8h" },
      { day: "Sat", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Sun", morning: "leave", afternoon: "leave", hours: "0h" },
    ],
    totalWeekHours: "35h 45m",
  },
  {
    id: 3,
    name: "Vu Duy Khanh",
    role: "QA",
    avatar: "VD",
    weekSchedule: [
      { day: "Mon", morning: "office", afternoon: "office", hours: "8h 30m" },
      { day: "Tue", morning: "office", afternoon: "office", hours: "8h" },
      { day: "Wed", morning: "office", afternoon: "office", hours: "8h 15m" },
      { day: "Thu", morning: "remote", afternoon: "remote", hours: "7h 30m" },
      { day: "Fri", morning: "office", afternoon: "office", hours: "8h" },
      { day: "Sat", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Sun", morning: "leave", afternoon: "leave", hours: "0h" },
    ],
    totalWeekHours: "40h 15m",
  },
  {
    id: 4,
    name: "Nguyen Thi Kieu Thanh",
    role: "PM/SM",
    avatar: "NT",
    weekSchedule: [
      { day: "Mon", morning: "remote", afternoon: "remote", hours: "8h" },
      { day: "Tue", morning: "remote", afternoon: "remote", hours: "7h 45m" },
      { day: "Wed", morning: "remote", afternoon: "leave", hours: "4h" },
      { day: "Thu", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Fri", morning: "remote", afternoon: "remote", hours: "8h" },
      { day: "Sat", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Sun", morning: "leave", afternoon: "leave", hours: "0h" },
    ],
    totalWeekHours: "27h 45m",
  },
  {
    id: 5,
    name: "Le Quoc Huy",
    role: "BE",
    avatar: "LQ",
    weekSchedule: [
      { day: "Mon", morning: "remote", afternoon: "office", hours: "8h" },
      { day: "Tue", morning: "office", afternoon: "leave", hours: "4h" },
      { day: "Wed", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Thu", morning: "remote", afternoon: "remote", hours: "6h 30m" },
      { day: "Fri", morning: "office", afternoon: "remote", hours: "7h 45m" },
      { day: "Sat", morning: "leave", afternoon: "leave", hours: "0h" },
      { day: "Sun", morning: "leave", afternoon: "leave", hours: "0h" },
    ],
    totalWeekHours: "26h 15m",
  },
];

export const employees = [
  {
    id: 1,
    name: "Do Thi Nga",
    role: "FE",
    avatar: "DN",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 15m",
  },
  {
    id: 2,
    name: "Luong Quy Tan",
    role: "FE",
    avatar: "LQ",
    currentStatus: "remote",
    schedule: [
      { time: "8:00-12:00", status: "remote", label: "🏠 Remote" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "4h 30m",
  },
  {
    id: 3,
    name: "Vu Duy Khanh",
    role: "QA",
    avatar: "VD",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 45m",
  },
  {
    id: 4,
    name: "Nguyen Thi Kieu Thanh",
    role: "PM/SM",
    avatar: "NT",
    currentStatus: "remote",
    schedule: [
      { time: "8:00-12:00", status: "remote", label: "🏠 Remote" },
      { time: "13:00-17:00", status: "remote", label: "🏠 Remote" },
    ],
    workTime: "7h 15m",
  },
  {
    id: 5,
    name: "Nguyen Xuan Hung",
    role: "QA",
    avatar: "NX",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 30m",
  },
  {
    id: 6,
    name: "Nguyen Thi My Khanh",
    role: "HR",
    avatar: "NM",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 50m",
  },
  {
    id: 7,
    name: "Le Quoc Huy",
    role: "BE",
    avatar: "LQ",
    currentStatus: "leave",
    schedule: [
      { time: "8:00-12:00", status: "remote", label: "🏠 Remote" },
      { time: "13:00-17:00", status: "leave", label: "😴 On Leave" },
    ],
    workTime: "3h 45m",
  },
  {
    id: 8,
    name: "Nguyen Thanh Nam",
    role: "Partner",
    avatar: "NT",
    currentStatus: "remote",
    schedule: [
      { time: "8:00-12:00", status: "remote", label: "🏠 Remote" },
      { time: "13:00-17:00", status: "remote", label: "🏠 Remote" },
    ],
    workTime: "6h 20m",
  },
  {
    id: 9,
    name: "Nguyen Duy Huy Tin",
    role: "FE",
    avatar: "ND",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 20m",
  },
  {
    id: 10,
    name: "Diep Minh Huy",
    role: "Management",
    avatar: "DM",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "remote", label: "🏠 Remote" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "6h 45m",
  },
  {
    id: 11,
    name: "Phan Thi Thanh Thao",
    role: "IA",
    avatar: "PT",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "7h 50m",
  },
  {
    id: 12,
    name: "Nguyen Thi Ha",
    role: "PM/SM",
    avatar: "NH",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "7h 30m",
  },
  {
    id: 13,
    name: "Pham Vu Dat",
    role: "BE",
    avatar: "PV",
    currentStatus: "leave",
    schedule: [
      { time: "8:00-12:00", status: "leave", label: "😴 On Leave" },
      { time: "13:00-17:00", status: "leave", label: "😴 On Leave" },
    ],
    workTime: "0h",
  },
  {
    id: 14,
    name: "Bui Thi Ngoc Huyen",
    role: "HR",
    avatar: "BT",
    currentStatus: "office",
    schedule: [
      { time: "8:00-12:00", status: "office", label: "🏢 Office" },
      { time: "13:00-17:00", status: "office", label: "🏢 Office" },
    ],
    workTime: "8h 40m",
  },
];
